name: Generate Google Token
on:
  workflow_dispatch:
    inputs:
      auth_code:
        description: 'Paste the Authorization Code here (leave empty for first run)'
        required: false
        default: ''

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install google-auth-oauthlib

      - name: Run Auth Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          INPUT_AUTH_CODE: ${{ github.event.inputs.auth_code }}
        run: |
          # If the input box is empty, print the link.
          if [ "$INPUT_AUTH_CODE" == "" ]; then
            python auth_generator_github.py
            echo "::error::Please click the link in the log to get the code, and then run this Workflow again, entering the code."
            exit 1
          else
            # If there is code, execute the logic for exchanging tokens.
            python auth_generator_github.py
          fi