name: Receive Contact from Shortcut

on:
  repository_dispatch:
    types: [sync_contacts] # 对应快捷指令中的 event_type

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run sync script
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python sync_test.py

      - name: Print Contact Info
        run: |
          echo "receive new contact："
          echo "name: ${{ github.event.client_payload.fname }} ${{ github.event.client_payload.lname }}"
          echo "phone number: ${{ github.event.client_payload.phone }}"
          echo "sync time: $(date)"
