name: Receive Contact from Shortcut

on:
  repository_dispatch:
    types: [sync_contacts] # has to be the same in shortcuts: event_type

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run sync script
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python execute.py

